### PR TITLE
Allow to log only on specific log targets

### PR DESCRIPTION
**Pull request by creekorful**
This PR should allow to log only on specific log targets thus preventing any non-wanted spamming from dependencies.

Closes: #15

### CODE REVIEW

**Comment by creekorful** [comment]
Hello @borntyping, should be good! 👍🏻 

Just let me know if you prefer another way of doing it.

BTW I think you should consider using builder pattern for instantiating SimpleLogger, this would make thing "proper", what do you think? I can manage a PR if you consider it.

Cheers!

**Comment by borntyping** [comment]
Adding a builder pattern would be great, though I'd like to keep the existing `init()` methods around for backwards compatibility (changing how those work internally to use a builder is fine).

**Comment by creekorful** [comment]
I will take a look! 
Thank you!

**Comment by piegamesde** [comment]
Blacklisting instead of this might have suited my average use case (some single too verbose dependency) better, but this will do as well.

If there is no plan to implement some wildcards e.g. through prefix matching, the `whitelisted_targets` could be stored as a `BTreeSet` instead.

**Comment by creekorful** [comment]
@piegamesde I think whitelisting make more sense no? I.e either you log everything or you choose what you want to be logged.

Thanks for suggestion! I will change to BTreeSet when I manage the "builder" PR.

**Comment by piegamesde** [comment]
I think plain whitelisting comes with the disadvantage of discoverability. How would you know the dependency you just added will log interesting things if you have to enable it first? The other way around, disabling all modules that are too verbose works better in this regard.

My other fear is that you have to explicitly write down every module and any of its submodules for logging. This can make a long list and brings the possibility of forgetting a more obscure submodule with rare but important log messages.

**Comment by borntyping** [comment]
Maybe the logger should take a filter, that can be `None`, `Show(targets)` or `Hide(targets)`?

**Comment by creekorful** [comment]
@borntyping I like the idea! Letting users choose wether to whitelist or blacklist seems the best way to go.

**Comment by piegamesde** [comment]
I like it as well, apart from some bike shedding maybe. But it depends on the name of the enum, if it is phrased as "filter" or as "which crates to log".

------

May I suggest a different idea? Have a `HashMap<String, LevelFilter>` which overrides the default log level. This would allow blacklisting by putting `LevelFilter::Off` for some paths. It would also allow for whitelisting by setting the level to off and then enabling single modules. It has the additional advantage of giving control over the actual log level instead of plain on/off semantics. The `enabled` function may look like this:

```rs
    fn enabled(&self, metadata: &Metadata) -> bool {
        metadata.level() <= self.target_levels.get(metadata.target()).unwrap_or(self.level);
    }
```

**Comment by creekorful** [comment]
@piegamesde I like it! It's a step further in customisation. I think it's the solution who offer the most configuration power for end users without being too complicated.

**Comment by borntyping** [comment]
I like this option too.

**Comment by borntyping** [comment]
Might be worth renaming the existing `level` to `default_level`?

**Comment by creekorful** [comment]
> I like this option too.

I can definitely implement it with the "Builder" PR if you want.

> Might be worth renaming the existing level to default_level?

Sure, I think it make more sense!

**Pull request merged**
